name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and test
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.2.0'

      - name: 🔧 Install dependencies
        run: npm ci

      - name: 🧪 Run Tests
        run: npm run test

      - name: 🚀 Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: 🔧 Install gitmoji-changelog
        run: npm install -g gitmoji-changelog

      - name: 📝 Generate Changelog
        run: gitmoji-changelog

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ':robot: chore(release): update changelog [skip ci]'
