name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.2.0'

      - name: 🔧 Install dependencies
        run: npm ci

      - name: 🧪 Run Tests and Generate Coverage
        run: npm run coverage

      - name: 📁 Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: cobertura-coverage# optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

